Repository stolostron/volsync-operator-product-build, pull requests merged in 2025-09, with the labels that each got.

#244 [release-0.14] Correct bundle channel version
  bundle.Dockerfile.rhtap
Labels: lgtm, approved

#262 [release-0.12] Do not build bundle when rpms.lock* is updated
  .tekton/volsync-bundle-0-12-pull-request.yaml
  .tekton/volsync-bundle-0-12-push.yaml
Labels: lgtm, approved

#263 [release-0.13] Do not build bundle when rpms.lock* is updated
  .tekton/volsync-bundle-0-13-pull-request.yaml
  .tekton/volsync-bundle-0-13-push.yaml
Labels: lgtm, approved

#264 [release-0.14] Do not build bundle when rpms.lock* is updated
  .tekton/volsync-bundle-0-14-pull-request.yaml
  .tekton/volsync-bundle-0-14-push.yaml
Labels: lgtm, approved

#293 chore(KONFLUX-6210): fix and set name and cpe label for volsync-bundle-0-13
  bundle.Dockerfile.rhtap
Labels: lgtm, approved, ok-to-test

#307 [release-0.12] chore(KONFLUX-6210): fix and set name and cpe label for volsync-bundle-0-12
  bundle.Dockerfile.rhtap
Labels: approved

#310 [release-0.14] chore(KONFLUX-6210): fix and set name and cpe label for volsync-0-14
  Dockerfile.rhtap
Labels: lgtm, approved

#356 [Release 0.13] common pipeline
  .tekton/volsync-0-13-pull-request.yaml
  .tekton/volsync-0-13-push.yaml
  .tekton/volsync-bundle-0-13-pull-request.yaml
  .tekton/volsync-bundle-0-13-push.yaml
Labels: lgtm, approved

#367 [release-0.14] build bundle if yq updated
  .tekton/volsync-bundle-0-14-pull-request.yaml
  .tekton/volsync-bundle-0-14-push.yaml
Labels: lgtm, approved
